// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
#include "packet.h"
#include <stdlib.h>
#include <string.h>

// Imported Functions from `component:quest-v1/host-console`

__attribute__((__import_module__("component:quest-v1/host-console"), __import_name__("log")))
extern void __wasm_import_component_quest_v1_host_console_log(uint8_t *, size_t);

// Imported Functions from `component:quest-v1/host-quest-manager`

__attribute__((__import_module__("component:quest-v1/host-quest-manager"), __import_name__("register-task")))
extern void __wasm_import_component_quest_v1_host_quest_manager_register_task(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t);

__attribute__((__import_module__("component:quest-v1/host-quest-manager"), __import_name__("update-task")))
extern void __wasm_import_component_quest_v1_host_quest_manager_update_task(uint8_t *, size_t, uint8_t *, size_t, int32_t);

__attribute__((__import_module__("component:quest-v1/host-quest-manager"), __import_name__("notify-player")))
extern void __wasm_import_component_quest_v1_host_quest_manager_notify_player(uint8_t *, size_t);

// Imported Functions from `component:quest-v1/host-events`

__attribute__((__import_module__("component:quest-v1/host-events"), __import_name__("get-current-url")))
extern void __wasm_import_component_quest_v1_host_events_get_current_url(uint8_t *);

// Imported Functions from `component:quest-v1/host-content`

__attribute__((__import_module__("component:quest-v1/host-content"), __import_name__("register-item")))
extern void __wasm_import_component_quest_v1_host_content_register_item(uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t, uint8_t *, size_t);

// Exported Functions from `packet`



// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void component_quest_v1_engine_types_quest_id_free(component_quest_v1_engine_types_quest_id_t *ptr) {
  packet_string_free(ptr);
}

void component_quest_v1_engine_types_task_id_free(component_quest_v1_engine_types_task_id_t *ptr) {
  packet_string_free(ptr);
}

void component_quest_v1_host_quest_manager_quest_id_free(component_quest_v1_host_quest_manager_quest_id_t *ptr) {
  component_quest_v1_engine_types_quest_id_free(ptr);
}

void component_quest_v1_host_quest_manager_task_id_free(component_quest_v1_host_quest_manager_task_id_t *ptr) {
  component_quest_v1_engine_types_task_id_free(ptr);
}

void packet_string_set(packet_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void packet_string_dup(packet_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void packet_string_dup_n(packet_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void packet_string_free(packet_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void component_quest_v1_host_console_log(packet_string_t *msg) {
  __wasm_import_component_quest_v1_host_console_log((uint8_t *) (*msg).ptr, (*msg).len);
}

void component_quest_v1_host_quest_manager_register_task(component_quest_v1_host_quest_manager_quest_id_t *qid, component_quest_v1_host_quest_manager_task_id_t *tid, packet_string_t *description) {
  __wasm_import_component_quest_v1_host_quest_manager_register_task((uint8_t *) (*qid).ptr, (*qid).len, (uint8_t *) (*tid).ptr, (*tid).len, (uint8_t *) (*description).ptr, (*description).len);
}

void component_quest_v1_host_quest_manager_update_task(component_quest_v1_host_quest_manager_quest_id_t *qid, component_quest_v1_host_quest_manager_task_id_t *tid, component_quest_v1_host_quest_manager_status_t s) {
  __wasm_import_component_quest_v1_host_quest_manager_update_task((uint8_t *) (*qid).ptr, (*qid).len, (uint8_t *) (*tid).ptr, (*tid).len, (int32_t) s);
}

void component_quest_v1_host_quest_manager_notify_player(packet_string_t *message) {
  __wasm_import_component_quest_v1_host_quest_manager_notify_player((uint8_t *) (*message).ptr, (*message).len);
}

void component_quest_v1_host_events_get_current_url(packet_string_t *ret) {
  __attribute__((__aligned__(sizeof(void*))))
  uint8_t ret_area[(2*sizeof(void*))];
  uint8_t *ptr = (uint8_t *) &ret_area;
  __wasm_import_component_quest_v1_host_events_get_current_url(ptr);
  *ret = (packet_string_t) { (uint8_t*)(*((uint8_t **) (ptr + 0))), (*((size_t*) (ptr + sizeof(void*)))) };
}

void component_quest_v1_host_content_register_item(packet_string_t *id, packet_string_t *url, packet_string_t *title, packet_string_t *item_type) {
  __wasm_import_component_quest_v1_host_content_register_item((uint8_t *) (*id).ptr, (*id).len, (uint8_t *) (*url).ptr, (*url).len, (uint8_t *) (*title).ptr, (*title).len, (uint8_t *) (*item_type).ptr, (*item_type).len);
}

__attribute__((__export_name__("init")))
void __wasm_export_exports_packet_init(void) {
  exports_packet_init();
}

__attribute__((__export_name__("on-visit")))
void __wasm_export_exports_packet_on_visit(uint8_t * arg, size_t arg0) {
  packet_string_t arg1 = (packet_string_t) { (uint8_t*)(arg), (arg0) };
  exports_packet_on_visit(&arg1);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_packet(void);
__attribute__((used))
void __component_type_object_force_link_packet_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_packet();
}
