// Generated by `wit-bindgen` 0.50.0. DO NOT EDIT!
#ifndef __BINDINGS_PACKET_H
#define __BINDINGS_PACKET_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct packet_string_t {
  uint8_t*ptr;
  size_t len;
} packet_string_t;

typedef packet_string_t component_quest_v1_engine_types_quest_id_t;

typedef packet_string_t component_quest_v1_engine_types_task_id_t;

typedef uint8_t component_quest_v1_engine_types_status_t;

#define COMPONENT_QUEST_V1_ENGINE_TYPES_STATUS_LOCKED 0
#define COMPONENT_QUEST_V1_ENGINE_TYPES_STATUS_ACTIVE 1
#define COMPONENT_QUEST_V1_ENGINE_TYPES_STATUS_COMPLETED 2
#define COMPONENT_QUEST_V1_ENGINE_TYPES_STATUS_FAILED 3

typedef component_quest_v1_engine_types_quest_id_t component_quest_v1_host_quest_manager_quest_id_t;

typedef component_quest_v1_engine_types_task_id_t component_quest_v1_host_quest_manager_task_id_t;

typedef component_quest_v1_engine_types_status_t component_quest_v1_host_quest_manager_status_t;

// Imported Functions from `component:quest-v1/host-console`
extern void component_quest_v1_host_console_log(packet_string_t *msg);

// Imported Functions from `component:quest-v1/host-quest-manager`
// Register a simplified task (like a checkpoint)
extern void component_quest_v1_host_quest_manager_register_task(component_quest_v1_host_quest_manager_quest_id_t *qid, component_quest_v1_host_quest_manager_task_id_t *tid, packet_string_t *description);
// Update state of a task
extern void component_quest_v1_host_quest_manager_update_task(component_quest_v1_host_quest_manager_quest_id_t *qid, component_quest_v1_host_quest_manager_task_id_t *tid, component_quest_v1_host_quest_manager_status_t s);
// Notify player (Toast/Log)
extern void component_quest_v1_host_quest_manager_notify_player(packet_string_t *message);

// Imported Functions from `component:quest-v1/host-events`
// Check if player is on a specific URL
extern void component_quest_v1_host_events_get_current_url(packet_string_t *ret);

// Imported Functions from `component:quest-v1/host-content`
// Register a content item (page, video, etc.) that the player should visit
extern void component_quest_v1_host_content_register_item(packet_string_t *id, packet_string_t *url, packet_string_t *title, packet_string_t *item_type);

// Exported Functions from `packet`
void exports_packet_init(void);
void exports_packet_on_visit(packet_string_t *url);

// Helper Functions

void component_quest_v1_engine_types_quest_id_free(component_quest_v1_engine_types_quest_id_t *ptr);

void component_quest_v1_engine_types_task_id_free(component_quest_v1_engine_types_task_id_t *ptr);

void component_quest_v1_host_quest_manager_quest_id_free(component_quest_v1_host_quest_manager_quest_id_t *ptr);

void component_quest_v1_host_quest_manager_task_id_free(component_quest_v1_host_quest_manager_task_id_t *ptr);

// Sets the string `ret` to reference the input string `s` without copying it
void packet_string_set(packet_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void packet_string_dup(packet_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void packet_string_dup_n(packet_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void packet_string_free(packet_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
