
const proxy = new Proxy(() => 0, { get: () => proxy, apply: () => 0 });
export default proxy;
export const Pollable = proxy;
export const poll = proxy;
export const InputStream = proxy;
export const OutputStream = proxy;
export const Error = proxy;
export const Fields = proxy;
export const FutureIncomingResponse = proxy;
export const IncomingBody = proxy;
export const IncomingRequest = proxy;
export const IncomingResponse = proxy;
export const OutgoingBody = proxy;
export const OutgoingRequest = proxy;
export const OutgoingResponse = proxy;
export const ResponseOutparam = proxy;
export const terminalInput = proxy;
export const terminalOutput = proxy;
export const stderr = proxy;
export const stdout = proxy;
export const stdin = proxy;
export const monotonicClock = proxy;
export const wallClock = proxy;
export const filesystem = proxy;
export const getRandomBytes = proxy;
export const getRandomU64 = proxy;
